service: s3-with-lambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:GetObjectVersion"
      Resource:
        - "arn:aws:s3:::${file(config.json):S3_BUCKET}/*"


functions:
  uploader:
    handler: functions/handler.readS3File
    events:
      - s3:
          bucket: ${file(config.json):S3_BUCKET}
          event: s3:ObjectCreated:*
          existing: true

# you can add CloudFormation resource templates here
resources:
 Resources:
   s3WithLambda:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${file(config.json):S3_BUCKET}
